blank_issues_enabled: false
contact_links:
  - name: Forum
    url: https://community.vikunja.io/
    about: Feature Requests, Questions, configuration or deployment problems should be discussed in the forum.
  - name: Security-related issues
    url: https://vikunja.io/contact/#security
    about: For security concerns, please send a mail to security@vikunja.io instead of opening a public issue.
  - name: Chat on Matrix
    url: https://matrix.to/#/#vikunja:matrix.org
    about: Please ask any quick questions here.
  - name: Translations
    url: https://crowdin.com/project/vikunja
    about: Any problems or requests for new languages about translations should be handled in crowdin.
