baseurl: https://vikunja.io/docs/
title: Vikunja
theme: vikunja
enableRobotsTXT: true
canonifyURLs: true

pygmentsUseClasses: true

permalinks:
  post: /:year/:month/:title/
  doc: /:slug/
  page: /:slug/
  default: /:slug/

params:
  description: The to-do app to organize your life
  author: The Vikunja Authors
  website: https://vikunja.io
  plausibleEnabled: true
  plausibleDomain: vikunja.io
  plausibleURL: https://analytics.kolaente.de

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  page:
    - name: Home
      url: https://vikunja.io/en/
      weight: 10
    - name: Features
      url: https://vikunja.io/features
      weight: 20
    - name: Download
      url: https://vikunja.io/download
      weight: 30
    - name: Docs
      url: https://vikunja.io/docs
      weight: 40
    - name: Code
      url: https://code.vikunja.io/
      weight: 50
    - name: Community
      url: https://community.vikunja.io/
      weight: 60
    - name: Get it Hosted
      url: https://vikunja.cloud/?utm_source=io&utm_medium=io&utm_campaign=menu
      weight: 70
